### ISSUE TITLE
CELO token duality

### ISSUE THREAD

**Issue by karlb** [celo-org/op-geth#1]
```[tasklist]
### Tasks
- [x] Add transfer precompile (without token address check)
- [x] Add GoldToken
- [x] Test transfer via GoldToken's ERC20 interface
- [x] Check token address in transfer precompile
- [x] Update forkdiff output file to visualize the token duality feature
- [x] Add proper automated test
```

**Comment by karlb** [comment]
A first PR is available at https://github.com/celo-org/op-geth/pull/3. I'll wait for progress on the core contracts before trying to get this merged.
