### ISSUE TITLE
Fee Currencies - post testnet

### ISSUE THREAD

**Issue by karlb** [celo-org/op-geth#130]
See https://github.com/celo-org/op-geth/issues/62 for issues which are to be done before the testnet launch.
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/op-geth/issues/74
- [ ] https://github.com/celo-org/op-geth/issues/125
- [ ] https://github.com/celo-org/op-geth/issues/129
- [ ] https://github.com/celo-org/docs/issues/1325
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/355
```

P1 bugs have been moved to https://github.com/celo-org/op-geth/issues/185.

**Comment by piersy** [comment]
@karlb said we can probably adjust this scope to fit any timeline :D

**Comment by ezdac** [comment]
I moved the CIP-66 issue to an epic issue with sub-issue tasks #64 since it could be broken down into individual tasks for better estimation.

The individual initial time estimations are still missing there (the sum before was 120h), but I would like to wait on the input of @karlb and @carterqw2 (and whether they already came up with estimations) before putting in my own.

@lvpeschke @mcortesi
