### ISSUE TITLE
Fee Currencies

### ISSUE THREAD

**Issue by carterqw2** [celo-org/op-geth#62]
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/op-geth/issues/63
- [ ] https://github.com/celo-org/op-geth/pull/58
- [ ] https://github.com/celo-org/op-geth/issues/65
- [ ] https://github.com/celo-org/op-geth/issues/66
- [ ] https://github.com/celo-org/op-geth/issues/68
- [ ] https://github.com/celo-org/op-geth/issues/70
- [ ] https://github.com/celo-org/op-geth/issues/73
- [ ] https://github.com/celo-org/op-geth/issues/75
- [ ] https://github.com/celo-org/op-geth/issues/76
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/171
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/172
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/173
- [ ] https://github.com/celo-org/op-geth/issues/110
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/174
- [ ] https://github.com/celo-org/op-geth/issues/101
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/175
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/176
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/170
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/177
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/178
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/179
- [x] Update gasCurrency parameter to use FeeCurrencyDirectory
- [ ] https://github.com/celo-org/op-geth/issues/142
- [ ] https://github.com/celo-org/op-geth/issues/140
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/189
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/191
- [ ] https://github.com/celo-org/op-geth/issues/109
- [ ] https://github.com/celo-org/op-geth/pull/91
- [ ] https://github.com/celo-org/op-geth/issues/124
- [x] Update What's changed doc
```

See https://github.com/celo-org/op-geth/issues/130 for fee currency related tasks which are to be done after the testnet launch.

**Comment by mcortesi** [comment]
@karlb this has a deadline of June 7, but there doesn't seem to many things left, could you provide some insights on the deadline please?

**Comment by carterqw2** [comment]
@mcortesi, Karl was OOO. I set it to June 7 based taking into account the [estimates](https://docs.google.com/spreadsheets/d/1vNqCg0N3ggrxuZ4evT9KKAKc787hTjx3RhN0t9puGWM/edit#gid=1104216372) and our team plans.

**Comment by lvpeschke** [comment]
Most urgent issues tackled, now moving to tracing to check that it works with our assumptions.

**Comment by lvpeschke** [comment]
@karlb 
1. please provide a status update
2. please consider which tasks can be postponed to after testnet launch
3. please chat with @carterqw2 and @marekolszewski concerning list / directory naming

**Comment by karlb** [comment]
Status update:
* Implementation is done (but with only a few tests so far)
* All remaining issues are docs related and we can move most or all of them to after the testnet if necessary
* The make fee currencies work on state migrated from a testnet, https://github.com/celo-org/celo-blockchain-planning/issues/339 needs to be solved

**Comment by lvpeschke** [comment]
The new directory should be deployed to Alfajores before testing the migration "for real".

**Comment by karlb** [comment]
Done, followup tasks in https://github.com/celo-org/op-geth/issues/130.

Maybe there is work to be done on https://github.com/celo-org/celo-blockchain-planning/issues/188, but I don't think it makes sense to keep this epic open just for that.
