### ISSUE TITLE
Implement CIP-66 TX type

### ISSUE THREAD

**Issue by carterqw2** [celo-org/op-geth#64]
See [CIP-66](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0066.md).
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/op-geth/issues/189
- [ ] https://github.com/celo-org/op-geth/issues/190
- [ ] https://github.com/celo-org/op-geth/issues/191
- [ ] https://github.com/celo-org/op-geth/issues/196
- [ ] https://github.com/celo-org/op-geth/issues/195
- [ ] https://github.com/celo-org/op-geth/issues/192
- [ ] https://github.com/celo-org/op-geth/issues/193
- [ ] https://github.com/celo-org/op-geth/issues/194
- [ ] https://github.com/celo-org/op-geth/issues/112
```

**Comment by mcortesi** [comment]
@karlb i think having an single issue with 120hs of estimate will make it very hard for you to provide updated estimates along the way.

Most probably your thinking process for the estimate was to provide an estimate to each of the "tasks" in the tasklist, and the sum was 120hs. So maybe it's worth splitting into smaller tasks.

Similary. Are the items on the task able to be done in a vaccumm? Can you work on one of the times, and check them, then on the next? If that's the case, more reason to split it, since you DO have checkpoints. Even that most probably you need some "skeleton task" where you create some basic types. This will also allow you to split the tasks into many people.

cc @lvpeschke
